<a href="https://colab.research.google.com/github/drshahizan/BDM/blob/main/lab/submission/F4/lab1/F4_ans_lab1b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab 1b - Understanding Your Data:

Please use the Occupation [dataset](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user) for this exercise.

#Step 1. Import the necessary libraries

In [3]:
import pandas as pd

#Step 2. Import the dataset from [Occupation](https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user).

In [4]:
df= pd.read_table("https://raw.githubusercontent.com/drshahizan/dataset/main/pandas/u.user",sep='|')

#Step 3. Assign it to a variable called users and use the 'user_id' as index

In [5]:
users = df.set_index('user_id')

#Step 4. See the first 25 entries

In [6]:
users.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

#Step 5. See the last 10 entries

In [7]:
users.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

#Step 6. What is the number of observations in the dataset?

In [8]:
len(users.index)

943

OR

Solution 2:

In [9]:
users.shape[0]

943

OR

Solution 3:

In [10]:
users.count()

age           943
gender        943
occupation    943
zip_code      943
dtype: int64

#Step 7. What is the number of columns in the dataset?

In [11]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

OR

Solution 2:

In [12]:
users.shape[1]

4

#Step 8. Print the name of all the columns.

In [13]:
count=1

for col in users.columns:
  print (str(count) +".\t"+ col)
  count +=1

1.	age
2.	gender
3.	occupation
4.	zip_code

OR

Solution 2:

In [14]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

#Step 9. How is the dataset indexed?

In [16]:
users.index

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

#Step 10. What is the data type of each column?

In [17]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

#Step 11. Print only the occupation column

In [18]:
users[["occupation"]]

            occupation
user_id
1           technician
2                other
3               writer
4           technician
5                other
...                ...
939            student
940      administrator
941            student
942          librarian
943            student

[943 rows x 1 columns]

#Step 12. How many different occupations are in this dataset?

In [19]:
print('No of different occupations:')
users['occupation'].value_counts().count()

No of different occupations:

21

OR

Solution 2:

In [20]:
print("No of different occupations:")
print(users['occupation'].nunique())

No of different occupations:
21

OR

Solution 2:

In [21]:
unique_occupation =0
occupation_list=[]

for index in range(0,len(users['occupation'])):
  if users['occupation'].iloc[index] not in occupation_list:
    occupation_list.append(users['occupation'].iloc[index])
    unique_occupation +=1
print ("No of different occupations: \t" + str(unique_occupation))
print ("\n")
unique_occupation_df=pd.DataFrame(occupation_list,index=pd.RangeIndex(start=1,stop=(len(occupation_list)+1)),columns=["unique_occupation"])
print ("List of different occcupation: \n")
print (unique_occupation_df)

No of different occupations: 	21


List of different occcupation:

   unique_occupation
1         technician
2              other
3             writer
4          executive
5      administrator
6            student
7             lawyer
8           educator
9          scientist
10     entertainment
11        programmer
12         librarian
13         homemaker
14            artist
15          engineer
16         marketing
17              none
18        healthcare
19           retired
20          salesman
21            doctor

#Step 13. What is the most frequent occupation?

In [22]:
print("Top 10 most frequent occupation:\n")
pd.DataFrame(users["occupation"].value_counts().sort_values(ascending=False).head(10))

Top 10 most frequent occupation:

               occupation
student               196
other                 105
educator               95
administrator          79
engineer               67
programmer             66
librarian              51
writer                 45
executive              32
scientist              31

OR

Solution 2:

In [23]:
print("the most frequent occupation:")
users['occupation'].mode()

the most frequent occupation:

0    student
Name: occupation, dtype: object

#Step 14. Summarize the DataFrame.

In [24]:
users.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

#Step 15. Summarize all the columns

In [31]:
print("Summarize of all columns include objects and integer value : \n")
users.describe(include='all')

Summarize of all columns include objects and integer value :

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

#Step 16. Summarize only the occupation column

In [26]:
print ("summarize of occupation: \n")
users['occupation'].describe()

summarize of occupation:

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

#Step 17. What is the mean age of users?

In [27]:
users['age'].mean()

34.05196182396607

#Step 18. What is the age with least occurrence?

In [28]:
users['age'].value_counts().nsmallest()

7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64

OR

Solution 2:

In [29]:
users.age.value_counts().tail()

7     1
66    1
11    1
10    1
73    1
Name: age, dtype: int64